### ISSUE TITLE
Thank you for your nice work. When is code released?

### ISSUE THREAD

**Issue by justinday123** [muzishen/IMAGPose#1]
Thank you for your nice work. It's said code will be released before november. Now it's november 15th, when will be code released? Thank you.

**Comment by muzishen** [comment]
Considering the CVPR deadline and the supplementary materials, unfortunately, we’ll need to postpone our planned submission until the end of the month. Apologies for the inconvenience!

**Comment by muzishen** [comment]
Thanks!
